export const UPDATE_DATA_TO_SERVER = "UPDATE_DATA_TO_SERVER";
export const SEND_DATA_TO_SERVER = "SEND_DATA_TO_SERVER";
export const ADD_TO_TABLE = "ADD_TO_TABLE";
export const SET_ISLOGIN = "SET_ISLOGIN";
export const FETCH_DATA_FROM_SERVER = "FETCH_DATA_FROM_SERVER";
export const SET_POSITION = "SET_POSITION";
export const FETCH_CUSTOM_USER_DATA = "FETCH_CUSTOM_USER_DATA";
